---
# Main docs: https://docs.docker.com/engine/install/ubuntu/

- name: Check Linux distro
  fail:
    msg: OS is not Ubuntu
  when: ansible_distribution != 'Ubuntu'

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    state: present
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get Ubuntu release
  command: lsb_release -cs
  register: ubuntu_release
  changed_when: false

- name: Get architecture
  command: dpkg --print-architecture
  register: architecture
  changed_when: false

- name: Set up stable repository
  apt_repository:
    repo: |
      deb [arch={{ architecture.stdout }}]
      https://download.docker.com/linux/ubuntu
      {{ ubuntu_release.stdout }} stable
    state: present

- name: Install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Add user {{ ansible_user }} to docker group
  user:
    name: "{{ ansible_user }}"
    groups: [docker]
    append: true
