name: Run checks

on:
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install linters
        run: |
          sudo apt install -y ansible ansible-lint yamllint

      - name: Run yamllint
        run: yamllint --format colored --strict ./*/*.yml

      - name: Run ansible-lint
        run: ansible-lint ./*/*.yml
